### ISSUE TITLE
[CI/CD] Set up GitHub Actions for automated testing

### ISSUE THREAD

**Issue by bendavieshe3** [bendavieshe3/art-factory#32]
## Description
Set up continuous integration to run tests automatically on every push and pull request. This ensures code quality and catches issues early.

## Tasks
- [ ] Create `.github/workflows/` directory
- [ ] Create `test.yml` workflow file
- [ ] Configure Python environment setup
- [ ] Install dependencies and run tests
- [ ] Add test status badge to README
- [ ] Configure branch protection rules

## Workflow Configuration
```yaml
# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        FAL_KEY: ${{ secrets.FAL_KEY }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        python manage.py test main --settings=ai_art_factory.test_settings
```

## Additional Tasks
- [ ] Add secrets to GitHub repository settings
- [ ] Test workflow on a feature branch
- [ ] Document CI/CD setup in README
- [ ] Consider adding linting step (ruff/black)

## Acceptance Criteria
- [ ] Tests run automatically on push to main
- [ ] Tests run on all pull requests
- [ ] Failed tests block merging
- [ ] Test results are visible in PR
- [ ] README shows test status badge

## Priority
**HIGH** - CI/CD is essential for maintaining code quality in a team environment
