### ISSUE TITLE
Implement CI/CD pipeline with automated testing

### ISSUE THREAD

**Issue by bendavieshe3** [bendavieshe3/art-factory#46]
## Overview
Create a comprehensive GitHub Actions workflow for automated testing, coverage reporting, and quality gates to ensure consistent code quality and prevent regressions.

### GitHub Actions Workflow
Create `.github/workflows/django.yml`:

```yaml
name: Art Factory CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage
    - name: Run tests with coverage
      run: |
        coverage run manage.py test --settings=ai_art_factory.test_settings
        coverage report --fail-under=90
        coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v3
```

### Quality Gates
- **Coverage**: Minimum 90% line coverage
- **Performance**: Test suite completes in <2 minutes
- **Reliability**: All tests must pass consistently
- **Security**: Security tests included for new features

## Tasks
- [ ] Create `.github/workflows/` directory
- [ ] Implement Django CI workflow
- [ ] Configure Codecov integration
- [ ] Add status badges to README
- [ ] Set up branch protection rules
- [ ] Configure test result formatting
- [ ] Add performance benchmarking
- [ ] Document CI/CD process

## Features
- **Multi-Python Testing**: Test against Python 3.11 and 3.12
- **Coverage Integration**: Automatic coverage reporting
- **PR Comments**: Coverage reports in pull request comments
- **Status Checks**: Required status checks for merging
- **Performance Monitoring**: Test execution time tracking

## Acceptance Criteria
- [ ] CI runs on every push and PR
- [ ] Coverage reports uploaded to Codecov
- [ ] Status badges display current build status
- [ ] Failed tests prevent merging
- [ ] Performance benchmarks tracked
- [ ] Documentation includes CI/CD guidelines

## Dependencies
- Requires: Coverage reporting (#44)
- Requires: Resource management fixes (#45)

## Priority
**High** - Automates quality assurance

## Related
- Part of Testing Infrastructure Phase 1
- Enables continuous quality monitoring
