### ISSUE TITLE
Enhanced Product Viewing Features and Modal

### ISSUE THREAD

**Issue by bendavieshe3** [bendavieshe3/art-factory#65]
## Description
Create an enhanced product viewing experience with a full-featured modal that provides detailed information, navigation, and actions. This addresses the v0.2 requirement for "improved preview capability that lets the user easily review multiple products to triage generation outputs."

## User Stories
- As a user, I want to view products in a full-screen modal for better detail
- As a user, I want to navigate between products without closing the viewer
- As a user, I want to see all metadata and parameters used for generation
- As a user, I want to perform actions on products while viewing them
- As a user, I want to zoom and pan high-resolution images

### 1. Full-Screen Product Modal
- Responsive modal that maximizes viewing area
- Dark background for better image contrast
- Smooth transitions and animations
- Mobile-optimized touch gestures
- Keyboard navigation support

### 2. Image Viewing Capabilities
- **Zoom Controls**:
  - Zoom in/out buttons
  - Mouse wheel zoom
  - Pinch-to-zoom on mobile
  - Double-click to zoom
  - Reset zoom button
- **Pan Support**:
  - Click and drag to pan
  - Touch gestures on mobile
- **Fit Options**:
  - Fit to screen
  - Actual size (1:1)
  - Fill screen

### 3. Navigation Features
- Previous/Next buttons with keyboard shortcuts
- Thumbnail strip (collapsible)
- Quick jump to image by number
- Filtered navigation (only show favorites, project, etc.)
- Loading indicators for image transitions
- Preload adjacent images for smooth navigation

### 4. Information Panel
**Collapsible sidebar with:**
- Generation parameters (all fields)
- File information (size, dimensions, format)
- Timestamps (created, modified)
- Project/collection associations
- Original order details
- Variation relationships
- Cost information
- Generation time

### 5. Action Toolbar
**Quick actions available in viewer:**
- Download (multiple format options)
- Favorite/Unfavorite toggle
- Delete (with confirmation)
- Regenerate options:
  - Exact regeneration
  - Generate similar
  - Create variations
- Share/Export options
- Edit metadata
- Add to project/collection
- Copy parameters to clipboard

#### Known Opening Points:
1. **From Order Screen - Thumbnail Strip**: 
   - Click on any thumbnail in the recent orders section
   - Opens viewer with that specific product
   - Navigation context includes all products from that order
   
2. **From Order Screen - Preview Area**:
   - Click on the main preview image in order details
   - Opens viewer focused on the selected product
   - Can navigate through all products in the order
   
3. **From Inventory Screen**:
   - Click on any product card in the grid view
   - Opens viewer with that product
   - Navigation context includes all products in current filtered view
   - Maintains filter/search context for navigation

#### Additional Integration Points:
- Open from search results
- Deep linking to specific product via URL
- Return to previous context after closing
- API endpoint for external integrations

### Modal Component Structure
```javascript
class ProductViewerModal {
    constructor() {
        this.currentProduct = null;
        this.products = [];
        this.currentIndex = 0;
        this.zoom = 1;
        this.panX = 0;
        this.panY = 0;
        this.openingContext = null; // 'order', 'inventory', etc.
    }
    
    open(productId, options = {}) {
        // Options can include:
        // - productList: array of products for navigation
        // - context: 'order', 'inventory', 'search'
        // - orderId: if opened from order context
        // - returnUrl: where to go when closed
        
        this.openingContext = options.context;
        this.products = options.productList || [productId];
        
        // Load product data
        // Setup modal
        // Preload adjacent images
        // Initialize controls
    }
    
    navigate(direction) {
        if (direction === 'next' && this.currentIndex < this.products.length - 1) {
            this.currentIndex++;
        } else if (direction === 'prev' && this.currentIndex > 0) {
            this.currentIndex--;
        }
        
        this.loadProduct(this.products[this.currentIndex]);
        this.preloadAdjacent();
    }
    
    setupZoomPan() {
        // Mouse wheel zoom
        this.imageContainer.addEventListener('wheel', (e) => {
            e.preventDefault();
            const delta = e.deltaY > 0 ? 0.9 : 1.1;
            this.setZoom(this.zoom * delta);
        });
        
        // Drag to pan
        let isDragging = false;
        let startX, startY;
        
        this.imageContainer.addEventListener('mousedown', (e) => {
            isDragging = true;
            startX = e.clientX - this.panX;
            startY = e.clientY - this.panY;
        });
    }
}
```

### Modal HTML Structure
```html
<div class="product-viewer-modal" id="productViewer">
    <div class="viewer-container">
        <!-- Main viewing area -->
        <div class="viewer-main">
            <!-- Navigation -->
            <button class="nav-button nav-prev" aria-label="Previous">
                <i class="bi bi-chevron-left"></i>
            </button>
            <button class="nav-button nav-next" aria-label="Next">
                <i class="bi bi-chevron-right"></i>
            </button>
            
            <!-- Image container -->
            <div class="image-container">
                <img class="product-image" alt="">
                <div class="loading-spinner" style="display: none;">
                    <div class="spinner-border"></div>
                </div>
            </div>
            
            <!-- Zoom controls -->
            <div class="zoom-controls">
                <button class="zoom-in" title="Zoom In">
                    <i class="bi bi-zoom-in"></i>
                </button>
                <button class="zoom-out" title="Zoom Out">
                    <i class="bi bi-zoom-out"></i>
                </button>
                <button class="zoom-reset" title="Reset">
                    <i class="bi bi-arrows-angle-expand"></i>
                </button>
                <span class="zoom-level">100%</span>
            </div>
            
            <!-- Close button -->
            <button class="close-button" aria-label="Close">
                <i class="bi bi-x-lg"></i>
            </button>
        </div>
        
        <!-- Information sidebar -->
        <div class="viewer-sidebar">
            <div class="sidebar-header">
                <h3>Product Details</h3>
                <button class="sidebar-toggle">
                    <i class="bi bi-chevron-right"></i>
                </button>
            </div>
            
            <div class="sidebar-content">
                <!-- Action buttons -->
                <div class="action-buttons">
                    <button class="btn btn-primary">
                        <i class="bi bi-download"></i> Download
                    </button>
                    <button class="btn btn-outline-primary">
                        <i class="bi bi-heart"></i> Favorite
                    </button>
                    <button class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-repeat"></i> Regenerate
                    </button>
                </div>
                
                <!-- Information sections -->
                <div class="info-section">
                    <h4>Generation Parameters</h4>
                    <dl class="parameters-list">
                        <!-- Dynamically populated -->
                    </dl>
                </div>
                
                <div class="info-section">
                    <h4>File Information</h4>
                    <dl>
                        <dt>Dimensions</dt>
                        <dd class="file-dimensions"></dd>
                        <dt>File Size</dt>
                        <dd class="file-size"></dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Thumbnail strip (optional) -->
    <div class="thumbnail-strip">
        <!-- Dynamically populated -->
    </div>
</div>
```

### CSS Styling
```css
.product-viewer-modal {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.95);
    z-index: 9999;
    display: flex;
    flex-direction: column;
}

.viewer-container {
    display: flex;
    flex: 1;
    overflow: hidden;
}

.viewer-main {
    flex: 1;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
}

.image-container {
    position: relative;
    overflow: hidden;
    cursor: grab;
    max-width: 100%;
    max-height: 100%;
}

.image-container.dragging {
    cursor: grabbing;
}

.product-image {
    transition: transform 0.2s ease;
    max-width: 100%;
    max-height: 100vh;
    object-fit: contain;
}

.viewer-sidebar {
    width: 320px;
    background: var(--bs-dark);
    color: var(--bs-light);
    overflow-y: auto;
    transition: transform 0.3s ease;
}

.viewer-sidebar.collapsed {
    transform: translateX(100%);
}

/* Mobile responsive */
@media (max-width: 768px) {
    .viewer-sidebar {
        position: absolute;
        right: 0;
        top: 0;
        height: 100%;
        width: 80%;
    }
    
    .nav-button {
        font-size: 1.5rem;
        padding: 0.5rem;
    }
}
```

### Phase 1: Basic Modal
1. Create modal structure
2. Implement open/close functionality
3. Display product image
4. Show basic metadata

### Phase 2: Navigation & Controls
1. Add previous/next navigation
2. Implement keyboard shortcuts
3. Add zoom functionality
4. Enable pan support

### Phase 3: Full Features
1. Information sidebar
2. Action buttons
3. Thumbnail strip
4. Touch gestures
5. Preloading logic

## Acceptance Criteria
- [ ] Modal opens with smooth animation
- [ ] Image displays at optimal size
- [ ] Navigation between products works
- [ ] Zoom and pan controls functional
- [ ] All metadata displayed clearly
- [ ] Actions work from within viewer
- [ ] Mobile gestures supported
- [ ] Keyboard navigation works
- [ ] Performance acceptable with large images
- [ ] Accessibility standards met
- [ ] Opens correctly from Order screen thumbnail strip
- [ ] Opens correctly from Order screen preview area
- [ ] Opens correctly from Inventory screen with proper context

## Priority
**HIGH** - Essential for reviewing and triaging generation outputs
