### ISSUE TITLE
Improve UI Information Density for Scale

### ISSUE THREAD

**Issue by bendavieshe3** [bendavieshe3/art-factory#79]
## Description
Optimize the overall UI information density to better support managing 250-1000 products as specified in the v0.2 Amateur 1 milestone. This focuses on UI-wide improvements beyond just inventory-specific enhancements.

## User Stories
- As a user managing 250+ products, I want more information visible without scrolling
- As a user, I want consistent, compact UI elements that don't waste screen space
- As a user, I want efficient navigation between different sections
- As a user, I want key information accessible at a glance

## Scope
This issue focuses on **global UI density improvements** across the application, complementing the inventory-specific work in issues #60 and #25.

### 1. Header and Navigation
- Reduce header height and padding
- Compact navigation menu
- Add breadcrumb navigation for context
- Quick stats in header (total products, active orders)

### 2. Production Counter Display
- More compact counter layout
- Inline stats instead of large blocks
- Progress indicators using less vertical space

### 3. Page Layout Optimization
- Reduce page margins and padding globally
- Optimize whitespace usage
- Implement responsive grid systems
- Better use of horizontal space

### 4. Typography and Spacing
- Review font sizes for optimal information density
- Reduce line height where appropriate
- Optimize form field spacing
- Compact button sizes

### 5. Sidebar and Panels
- Collapsible/expandable panels
- Sticky positioning for key controls
- Compact filter panels
- Efficient use of sidebar real estate

### CSS Framework Optimization
```css
/* Global density improvements */
.compact-layout {
    --spacing-sm: 0.25rem;
    --spacing-md: 0.5rem;
    --spacing-lg: 0.75rem;
}

/* Header compression */
.main-header {
    height: 3.5rem; /* Reduced from 4rem */
    padding: 0.5rem 1rem; /* Reduced padding */
}

/* Form density */
.form-group {
    margin-bottom: 0.75rem; /* Reduced from 1rem */
}

/* Compact navigation */
.nav-link {
    padding: 0.375rem 0.75rem; /* Reduced padding */
}
```

### Responsive Breakpoints
- Optimize for common screen sizes (1920x1080, 1366x768)
- Ensure density improvements work on tablets
- Maintain mobile usability

### JavaScript Enhancements
- Dynamic content sizing
- Collapsible sections with state persistence
- Efficient pagination controls
- Quick access shortcuts

### Phase 1: Global Layout (Week 1)
1. Header and navigation compression
2. Page margin optimization
3. Typography review and adjustment
4. Basic spacing improvements

### Phase 2: Component Density (Week 2)
1. Form field optimization
2. Button sizing improvements
3. Panel and sidebar efficiency
4. Progress indicator compression

### Phase 3: Advanced Features (Week 3)
1. Collapsible sections
2. Quick access shortcuts
3. Dynamic sizing features
4. Performance optimization

### Information Hierarchy
- Maintain clear visual hierarchy despite density
- Ensure important actions remain prominent
- Balance density with usability

### Accessibility
- Maintain minimum touch target sizes (44px)
- Preserve readable font sizes
- Ensure adequate color contrast
- Support keyboard navigation

### Performance
- Minimize layout reflows
- Optimize CSS for rendering performance
- Consider virtual scrolling for large lists

## Acceptance Criteria
- [ ] Overall page content density increased by 20-30%
- [ ] More products visible per screen in all views
- [ ] Navigation and headers use less vertical space
- [ ] Form layouts are more compact but still usable
- [ ] Mobile responsiveness maintained
- [ ] Accessibility standards met
- [ ] Performance impact is minimal
- [ ] User testing validates improved efficiency
- [ ] Documentation updated with new design patterns

## Integration with Related Issues
- **Complements #60** (Inventory filtering) with density improvements
- **Supports #57** (Projects) with compact project selection
- **Enhances #58** (Templates) with efficient template displays
- **Works with #61** (Bulk operations) for compact selection UI

## Priority
**HIGH** - Essential for v0.2's 250-1000 product scale requirement

## Notes
- This is a UI/UX focused issue complementing the functional improvements in other issues
- Should be coordinated with the Product Card optimization issue
- Consider user testing to validate density improvements don't hurt usability
